### ISSUE TITLE
No error message when clicked "add" button without any input.

### ISSUE THREAD

**Issue by phanindra789** [LibreHealthIO/lh-ehr#893] opened 2017-12-26 16:21 UTC
There are many blue colored "add" buttons in various sections of "Search or Add Patient" to add names of Countries, States, Occupation, Cities etc. 
When clicked "Add" without any input, there is no intimation that I left them blank.
 At least, an error message should be displayed when left something blank.

**Comment by MigDinny** [comment] 2017-12-26 16:56
Currently, when you click on "Add" button and you left everything in blank, the popup doesn't hide, that means that there is no problem. 

Example:

![image](https://user-images.githubusercontent.com/6632800/34360938-7789d976-ea5d-11e7-9c6f-f58f3a617694.png)

When you click on "add" button with an empty field, nothing happens. There is no need of any warning, in my opinion, because the popup doesn't hide itself and that is enough to "warn" the user, I think.

**Comment by phanindra789** [comment] 2017-12-26 17:00
But it should say something like "Please enter something..." instead of staring at me. :D

**Comment by MigDinny** [comment] 2017-12-26 17:41
@phanindra789 Well, I don't think it's needed, but you can do it in a pull request and wait for mentor's review :)

**Comment by pri2si17-1997** [comment] 2017-12-26 18:57
@phanindra789 This is not a bug. Instead of adding any message you can just create the border as red IMO. @MigDinny is right. Popup is not hiding, and that is enough for user to warn. :slightly_smiling_face:

**Comment by MigDinny** [comment] 2017-12-26 19:29
@pri2si17-1997 That's a good idea! turning border into red would be nice.

**Comment by aethelwulffe** [comment] 2017-12-27 15:11
@phanindra789  Hi Sai, yeah, it would be cool if you wanted to do a non-obtrusive alert like a color change.  Personally, I have always wanted to do fading messages in the background "Form Incomplete!".  You know, sort of like when Mario grabs a coin and a 1 Yen symbol appears briefly.  There is, of course, the classic "DOINK!" error sound, but audible alerts are not very effective unless the user has speakers.  I have noticed that monitors are generally always used 😄

**Comment by MigDinny** [comment] 2017-12-27 15:26
@aethelwulffe I personally think that fading messages like those would be a little bit annoying for simple stuff like this :)

**Comment by aethelwulffe** [comment] 2017-12-27 15:41
Agreed... but we should probably institute classes that do things like that (in a standardized way) at some point.  Navigation away from a page, momentary notifications that appear and disappear automatically without requiring user input and all that would go a good way towards N00b errors is use.  Very often a clinician will enter data into a form, navigate away without saving, then describe the problem with "It wont let me" or some similar description commonly used by the technically challenged.  Sanity checks and input error reporting is a good thing to have standardized across an application, I am sure we agree.  All the same, *eventually* someone will catch on if the modal window just keeps staring at them.
@phanindra789 if you want to take on instituting a class that can change the add buttons to red after an input error, then keep this issue open.  Otherwise we should mark this as "won't fix".  Personally, I would like to see "save" or "submit" buttons greyed out (standardized, everywhere in the system) until required fields are completed.  This is not possible with pure php, but we are using a lot of js these days.

**Comment by Jdew192837** [comment] 2017-12-28 17:23
@aethelwulffe I know how to differ the button colors, I can do an issue about differing the add/cancel buttons to be blue and red if you would like

**Comment by aethelwulffe** [comment] 2018-05-03 13:44
General UI changes have passed this by...and a general "input warnings" library should be part of that, but closing this (with notes to include it as an example for a future project.

**Closed by aethelwulffe** 2018-05-03 13:44 UTC
